name: Genesis Engine CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Orchestrator (heartbeat)
        run: python orchestrator/genesis_orchestrator.py
      - name: Exercise components
        run: |
          python cli/commit_action.py --actor "CI" --kind DECISION --details "Approve Alpha"
          python digital_soul/generate_agent.py --name "PatientZero"
          python digital_soul/update_agent.py --name "PatientZero" --event "Institutional Betrayal"
          python veracity/ingest_evidence.py --src samples/evidence_sample.json
          python causal/simulate_causal.py --graph samples/causal_graph.json --do "PolicyBlock=1" --steps 12
      - name: Build manifest + card
        run: |
          python tools/build_manifest.py --root . --out artifacts
          python tools/build_artifact_card.py --out artifacts
      - name: Claim guard
        run: python claim_guard/claim_guard.py
      - name: Optional sign
        if: ${{ hashFiles('keys/private.key') != '' }}
        run: python tools/ed25519_sign.py sign --priv keys/private.key --file artifacts/MANIFEST_SHA256.txt --out artifacts/MANIFEST_SHA256.txt.sig
